name: Print Secret & Env Var

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  print-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Repository Secret
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          # This is for testing purposes only - printing secrets is normally not recommended
          # GitHub automatically masks secrets in logs, so we'll use a workaround
          echo "::warning::Secret value is: ${MY_SECRET}"
          # Alternative method to reveal the secret (for testing only)
          echo "${MY_SECRET}" | sed 's/./& /g'

  print-env-var:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Repository Var
        env:
          MY_VAR: ${{ vars.MY_VAR }}
        run: |
            echo "env var value is: ${MY_VAR}"
